import Head from 'next/head'
import Image from 'next/image'

import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Images</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="https://img.mobigama.net/app/6938-yandex/1_yandex.png" />
      </Head>

      <main className={styles.main}>
        
      </main>
    </div>
  )
}
